---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/tasks.json
- name: Ensure a module path is defined
  ansible.builtin.assert:
    that:
      - terraform_module_source is defined
    fail_msg: "terraform_module_source must be defined"

- name: Ensure either a backend or work directory is defined
  ansible.builtin.assert:
    that:
      - terraform_module_workdir is defined or terraform_module_backend_config != terraform_module_backend_config_default
    fail_msg: "Either terraform_module_workdir or terraform_module_backend_config must be defined to avoid discarding state."
  vars:
    terraform_module_backend_config_default:
      local: {}

- name: Ensure terraform_module_action is valid
  ansible.builtin.assert:
    that:
      - terraform_module_action is defined
      - terraform_module_action in ['plan-apply', 'plan-destroy', 'apply', 'destroy']
    fail_msg: "terraform_module_action must be one of: plan-apply, plan-destroy, apply, destroy. Got: {{ terraform_module_action }}"
    success_msg: "terraform_module_action is valid: {{ terraform_module_action }}"

- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: terraform_module_temporary_directory
  when: terraform_module_workdir is not defined
  check_mode: false

- name: Set working directory from temporary directory
  ansible.builtin.set_fact:
    _terraform_module_workdir: "{{ terraform_module_temporary_directory['path'] }}"
  when: terraform_module_workdir is not defined

- name: Set working directory from variable
  ansible.builtin.set_fact:
    _terraform_module_workdir: "{{ terraform_module_workdir }}"
  when: terraform_module_workdir is defined

- name: Determine if we should generate a plan or not (no)
  ansible.builtin.set_fact:
    _terraform_module_should_plan: false
    _terraform_module_plan_file: "{{ terraform_module_plan_file_input }}"
  when: terraform_module_plan_file_input is defined

- name: Determine if we should generate a plan or not (yes)
  ansible.builtin.set_fact:
    _terraform_module_should_plan: true
    _terraform_module_plan_file: "{{ inventory_hostname }}-plan.out"
  when: terraform_module_plan_file_input is not defined

- name: Write root module configuration
  ansible.builtin.template:
    src: main.tf.json.j2
    dest: "{{ _terraform_module_workdir }}/main.tf.json"
  vars:
    terraform_module_version_argument: "{{ terraform_module_version is defined | ternary({'version': terraform_module_version}, {}) }}"
    terraform_module_config_base:
      terraform:
        backend: "{{ terraform_module_backend_config }}"
      module:
        this: "{{ terraform_module_inputs | combine({'source': terraform_module_source}) | combine(terraform_module_version_argument) }}"
      output:
        this:
          value: "${module.this}"
          sensitive: true
    terraform_module_config: "{{ terraform_module_config_base | combine(terraform_module_extra) }}"

- name: Terraform init
  ansible.builtin.include_tasks: init.yml
  when: _terraform_module_should_plan or terraform_module_force_init

- name: Generate terraform plan
  ansible.builtin.include_tasks: plan.yml
  when: _terraform_module_should_plan

- name: Parse terraform plan
  ansible.builtin.include_tasks: parse-plan.yml

- name: Display the Terraform plan
  ansible.builtin.debug:
    var: terraform_module_plan
  when: terraform_module_preview_plan | ansible.builtin.bool

- name: Apply interactively
  ansible.builtin.include_tasks: apply-interactive.yml
  when:
    - not ansible_check_mode
    - terraform_module_interactive | ansible.builtin.bool
    - terraform_module_action == 'apply'
    - terraform_module_plan_has_changes

- name: Apply non-interactively
  ansible.builtin.include_tasks: apply-non-interactive.yml
  when:
    - not ansible_check_mode
    - not (terraform_module_interactive | ansible.builtin.bool)
    - terraform_module_action == 'apply'
    - terraform_module_plan_has_changes

- name: Destroy interactively
  ansible.builtin.include_tasks: destroy-interactive.yml
  when:
    - not ansible_check_mode
    - terraform_module_interactive | ansible.builtin.bool
    - terraform_module_action == 'destroy'
    - terraform_module_plan_has_changes

- name: Destroy non-interactively
  ansible.builtin.include_tasks: destroy-non-interactive.yml
  when:
    - not ansible_check_mode
    - not (terraform_module_interactive | ansible.builtin.bool)
    - terraform_module_action == 'destroy'
    - terraform_module_plan_has_changes

- name: Obtain outputs
  ansible.builtin.include_tasks: outputs.yml
  when: []

- name: Cleanup
  ansible.builtin.include_tasks: cleanup.yml
