galaxy_info:
  author: Iain Learmonth
  description: Deploy resources using a Terraform module
  company: SR2 Communications Limited
  issue_tracker_url: http://gitlab.com/sr2c/ansible-terraform/-/issues
  license: BSD-2
  min_ansible_version: 2.1
  platforms:
   - name: Fedora
     versions:
     - all
   - name: Debian
     versions:
     - all
  galaxy_tags: []

dependencies: []
